
name: CICD
on:
  workflow_dispatch: null
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "clone code from github"
  build:
    needs: [code]
    runs-on: ubuntu-latest
    
    steps:
      - name: build docker container
        run: echo "Docker container build"
  test:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - name: testing the code
        run: echo "Testing the code"
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
   
    steps:
      - name: deploying the app
        run: echo " deploying the app"
