#This is workflow name
#name: Hello 
#runs on a trigger
#on:
 # push:
  #  branches: [main]
#these are jobs inside the workflow
#jobs:

#this is name of the job
#greet:
 # runs-on: ubuntu-latest 
  #steps:
   # - name : say hello to users
    #  run : echo "Hello Dosto"

    #- name: say hello to username
     # run : echo "Hello $USER"

---
name: Hello
on:
  push:
    branches:
      - main
jobs:
 greet:
  runs-on: ubuntu-latest
  
  steps:
    - name: say hello to users
      run: echo "Hello Dosto"
      
    - name: say hello to username
      run: echo "Hello $USERNAME"
      
    - name: say hello to username
      run: echo "Hello $USER"
  showdetails:
   runs-on: ubuntu-latest

   steps:
     - name: version of python
       run: echo "python 3.2" 
